name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    name: Deploy Functions
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Deploy dice-auto-draw
        run: |
          deno run -A https://deno.land/x/supabase@1.17.3/functions/deploy.ts dice-auto-draw
        working-directory: ./supabase/functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: gtoofdphwneqpwsmjcwl
