name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.153.0
          
     - name: Clear Docker volumes
        run: docker system prune -af || true

      - name: Deploy Edge Function
        run: supabase functions deploy diceautodraw --project-ref gtoofdphwneqpwsmjcwl
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
