name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.153.0

      # ✅ 清理 GitHub Actions 运行环境中的 Docker 缓存
      - name: Clear Docker volumes (cleanup workaround)
        run: docker system prune -af || true

      - name: Deploy Edge Function
        run: supabase functions deploy diceautodraw --project-ref gtoofdphwneqpwsmjcwl
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
