name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.153.0

      - name: Deploy diceautodraw function
        run: |
          cd supabase/functions/dice-autodraw
          supabase functions deploy dice-autodraw --project-ref gtoofdphwneqpwsmjcwl --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
