name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.152.2

      - name: Deploy diceautodraw function
        run: |
          supabase functions deploy diceautodraw \
            --project-ref gtoofdphwneqpwsmjcwl \
            --no-verify-jwt \
            --workdir supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
